name: 'ComfyUI Node Validator'
description: 'Validates ComfyUI custom nodes for breaking changes'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  base_ref:
    description: 'Base branch to compare against'
    required: false
    default: 'main'

runs:
  using: 'composite'
  steps:
    - name: Checkout PR
      uses: actions/checkout@v3
      with:
        path: pr_repo
        
    - name: Checkout base
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.base_ref }}
        path: base_repo
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
      
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install typing-extensions
        
    - name: Run validation
      shell: bash
      run: |
        python ${{ github.action_path }}/src/validate_nodes.py base_repo pr_repo
